#!/usr/bin/env python3

"""
multi_hoster_uploader - A command-line tool to upload files to multiple file hosting services.

Author: Christopher Kreft <email@christopherkreft.de>
License: MIT
"""

import argparse
from hoster import MultiHosterManager
from hoster.hosters import FileIoHoster, GofileHoster, KeepShHoster
from sys import exit

# define the hoster classes to use in the order to try
HOSTERS = [FileIoHoster, GofileHoster, KeepShHoster]


def main():
    parser = argparse.ArgumentParser(description='Upload a file to various file hosting services.')
    parser.add_argument('-f', '--file', required=True, help='The file to upload')
    parser.add_argument('--random-hoster', action='store_true', help='Try hosters in random order')
    args = parser.parse_args()

    manager = MultiHosterManager(HOSTERS, random_hoster=args.random_hoster)
    download_url = manager.upload(args.file)

    if download_url:
        print(download_url)
        exit(0)
    else:
        print('Upload failed.')
        exit(2)


if __name__ == '__main__':
    main()
